# Generated by Django 3.1 on 2020-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordinstance',
            name='username',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
